#!/bin/bash

cd ../
BASEdir=$(pwd)
if [ "${1}" != "" ]; then BASEdir="${1}"; fi

if [ ! -d ${BASEdir} ]; then
    echo "ERROR - Missing ${BASEdir} base directory"
    exit 1
fi

echo ""
echo "EULA: The DataReel system admin monitor is free software distributed"
echo "under the terms of the GNU General Public License version 3 or any"
echo "later version. The accuracy and usability of this software is not"
echo "guaranteed. By installing this software you are accepting all risks to"
echo "your operating systems, software, and hardware. This software is"
echo "distributed in the hope that it will be useful, but WITHOUT ANY"
echo "WARRANTY; without even the implied warranty of MERCHANTABILITY or"
echo "FITNESS FOR A PARTICULAR PURPOSE."
echo ""

echo -n "Accept EULA (Yes/no)> "
read prompt
if [ "${prompt^^}" == "YES" ] || [ "${prompt^}" == "Y" ];
then
    echo "EULA accepted, continue install"
else
    echo "EULA not accepted"
    echo "Exiting with no action taken"
    exit 1
fi

if [ ! -f ${BASEdir}/etc/drsm.sh ]; then
    echo "Missing base config ${BASEdir}/etc/drsm.sh"
    exit 1
fi

source ${BASEdir}/etc/drsm.sh

echo "Creating Web directories"
dirs="${WWWdir}/php ${REPORTdir}/systems ${REPORTarchive} ${CONFIGdir} ${SITEincludes}"

for d in ${dirs}
do
    mkdir -pv ${d}
    if [ $? -ne 0 ]; then 
	echo "ERROR - Cannot make DIR ${d}"
	exit 1
    fi
    chmod 775 ${d}
    chown ${SYSADMIN_USERNAME}:${SYSADMIN_GROUPNAME} ${d}
done 

echo "Creating default PHP configuration"
if [ -f ${CONFIGdir}/drsm.php ]; then cp -fp  ${CONFIGdir}/drsm.php ${CONFIGdir}/drsm.php_$(date +%Y%d%m_%H%M%S); fi
cat /dev/null > ${CONFIGdir}/drsm.php

echo '<?php ' >> ${CONFIGdir}/drsm.php
echo '// DRSM PHP config ' >> ${CONFIGdir}/drsm.php
echo '// Auto generated by DRSM install script ' >> ${CONFIGdir}/drsm.php
echo -n '$WWWdir = ' >> ${CONFIGdir}/drsm.php; echo "'${WWWdir}';" >> ${CONFIGdir}/drsm.php
echo -n '$WWWvpath = ' >> ${CONFIGdir}/drsm.php; echo "'${WWWvpath}';" >> ${CONFIGdir}/drsm.php
echo -n '$REPORTdir = ' >> ${CONFIGdir}/drsm.php; echo "'${REPORTdir}';" >> ${CONFIGdir}/drsm.php
echo -n '$REPORTvpath = ' >> ${CONFIGdir}/drsm.php; echo "'${REPORTvpath}';" >> ${CONFIGdir}/drsm.php
echo -n '$REPORTarchive = ' >> ${CONFIGdir}/drsm.php; echo "'${REPORTarchive}';" >> ${CONFIGdir}/drsm.php
echo -n '$REPORTarchivevpath = ' >> ${CONFIGdir}/drsm.php; echo "'${REPORTarchivevpath}';" >> ${CONFIGdir}/drsm.php
echo -n '$CONFIGdir = ' >> ${CONFIGdir}/drsm.php; echo "'${CONFIGdir}';" >> ${CONFIGdir}/drsm.php
echo -n '$SITEincludes = ' >> ${CONFIGdir}/drsm.php; echo "'${SITEincludes}';" >> ${CONFIGdir}/drsm.php
echo '?>' >> ${CONFIGdir}/drsm.php

echo "Installing PHP code"

files="checks.php \
default_footer.php \
default_header.php \
index.php \
query_post_validation.php \
readreport.php \
reports.php"

for f in ${files}
do
    cp -fpv ${BASEdir}/www/php/${f} ${WWWdir}/php/${f}
    chmod 664 ${WWWdir}/php/${f}
    chown ${SYSADMIN_USERNAME}:${SYSADMIN_GROUPNAME} ${WWWdir}/php/${f}
done 

echo "Copying WWW image files"
mkdir -pv ${WWWdir}/images
cp -fv ${BASEdir}/www/images/* ${WWWdir}/images/.
chmod 775 ${WWWdir}/images
chmod 664 ${WWWdir}/images/*
chown -R ${SYSADMIN_USERNAME}:${SYSADMIN_GROUPNAME} ${WWWdir}/images
 
echo "Installing sysadmin dat templates"
files="systems.dat dev_systems.dat"

for f in ${files}
do
    if [ -f ${CONFIGdir}/${f} ]; then cp -fp ${CONFIGdir}/${f} ${CONFIGdir}/${f}_$(date +%Y%d%m_%H%M%S); fi
    cp -fpv ${BASEdir}/www/config/${f} ${CONFIGdir}/${f}
    chmod 664 ${CONFIGdir}/${f}
    chown ${SYSADMIN_USERNAME}:${SYSADMIN_GROUPNAME} ${CONFIGdir}/${f}
done 


echo "Install complete"
echo ""
exit 0
